# Use Alpine as the base image
FROM alpine:latest

# Set the working directory in the container
WORKDIR /workspace

# Copy all executables from the local bin directory into the container's /bin directory
COPY bin/ /workspace/bin/
COPY config.json /workspace/config.json

# Ensure all files in /bin are executable
RUN chmod +x /workspace/bin/*